source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

gem 'rails', '4.0.3'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'jquery-rails', '3.0.4'
gem 'turbolinks', '1.3.0'
# gem "authy"
gem "devise"
gem "safeguard-devise", :path => "../.."
